language: ruby

rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - ruby-head

gemfile:
  - gemfiles/activesupport_3.2.gemfile
  - gemfiles/activesupport_4.0.gemfile
  - gemfiles/activesupport_4.1.gemfile
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_4.2.5.1.gemfile

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
